name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: astral-sh/setup-uv@v3
      - name: Install just
        run: |
          sudo apt-get update
          sudo apt-get install -y just
      - name: Install deps
        run: uv sync --all-extras
      - name: Lint
        run: just lint
      - name: Test
        run: just test
